[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[[edge_functions]]
  path = "/shorten"
  function = "shorten"

[[edge_functions]]
  path = "/count"
  function = "count"

[[edge_functions]]
  path = "/latest"
  function = "latest"

[[edge_functions]]
  path = "/*"
  function = "redirect"
